# Generated by Django 4.1.1 on 2022-09-28 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=60)),
                ('salary', models.IntegerField()),
                ('education', models.CharField(max_length=60)),
                ('experience', models.TextField(blank=True)),
                ('portfolio', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
