# Generated by Django 4.1.1 on 2022-09-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_resume_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
