# Generated by Django 4.1.1 on 2022-09-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='owner',
        ),
    ]
